#!/usr/bin/env bash

FILE=${1:-db/schema.rb}

cat $FILE \
    | grep -v add_foreign_key \
    | grep -v t.index \
    | grep -v '^end$' \
    | grep -v 'ActiveRecord::Schema.define' \
    | grep -v '^#' \
    | grep -v 'These are extensions that must' \
    | grep -v 'plpgsql' \
    | perl -pe 's/create_table "([a-z_]+)".+$/type \1 {/' \
    | perl -pe 's/  end$/}/' \
    | perl -pe 's/string/String/' \
    | perl -pe 's/text/String/' \
    | perl -pe 's/integer/Number/' \
    | perl -pe 's/datetime/String/' \
    | perl -pe 's/boolean/Boolean/' \
    | perl -pe 's/t\.//' \
    | perl -pe 's/"//g' \
    | perl -pe 's/,.+//' \
    | perl -pe 's/^ +//g' \
    | perl -pe 's/([a-zA-Z_]+) (["a-zA-Z_]+)$/  \2: \1/' \
    | perl -pe 's/(_|^type )(.)/type \u\2/'
